- hosts: localhost
  gather_facts: true
  # Only if current user is sudoer
  # become_user: "{{ lookup('env', 'USER') }}"
  vars:
    user: "{{ ansible_user_id }}"
    home_dir: "{{ lookup('env', 'HOME') }}"
    source_ssh_key: "./.ssh/id_rsa"
    dest_ssh_key: "{{ home_dir }}/.ssh/id_rsa"
    source_ssh_config: "./.ssh/config"
    dest_ssh_config: "{{ home_dir }}/.ssh/config"
  pre_tasks:
    - name: Update apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - core
        - docker
        - node
        - python
  tasks:
    - name: Install core packages
      ansible.builtin.import_tasks:
        file: tasks/core.yml
      become: true
    - name: Setup SSH
      ansible.builtin.import_tasks:
        file: tasks/ssh.yml
    - name: Setup git config
      ansible.builtin.import_tasks:
        file: tasks/git.yml
    - name: Setup shell
      ansible.builtin.import_tasks:
        file: tasks/shell.yml
    - name: Install Docker
      ansible.builtin.import_tasks:
        file: tasks/docker.yml
      become: true
    - name: Install VSCode
      ansible.builtin.import_tasks:
        file: tasks/vscode.yml
      become: true
    - name: Install JetBrains Rider
      ansible.builtin.import_tasks:
        file: tasks/rider.yml
      become: true
    - name: Install JetBrains IntelliJ IDEA
      ansible.builtin.import_tasks:
        file: tasks/intellij.yml
      become: true
    - name: Install Node.js
      ansible.builtin.import_tasks:
        file: tasks/node.yml
      become: true
    - name: Install Deno
      ansible.builtin.import_tasks:
        file: tasks/deno.yml
    - name: Install Rust
      ansible.builtin.import_tasks:
        file: tasks/rust.yml
    - name: Install Java
      ansible.builtin.import_tasks:
        file: tasks/java.yml
    - name: Install Python
      ansible.builtin.import_tasks:
        file: tasks/python.yml
    - name: Install Brave browser
      ansible.builtin.import_tasks:
        file: tasks/brave-browser.yml
      become: true
    - name: Install Slack
      ansible.builtin.import_tasks:
        file: tasks/slack.yml
      become: true
    - name: Install KeePassXC
      ansible.builtin.import_tasks:
        file: tasks/keepass.yml
      become: true
    - name: Install Kubectl
      ansible.builtin.import_tasks:
        file: tasks/kubectl.yml
      become: true
    - name: Install AWS CLI (v2)
      ansible.builtin.import_tasks:
        file: tasks/aws.yml
      become: true
    - name: Setup dev environment
      ansible.builtin.import_tasks:
        file: tasks/dev.yml
      become: true
# # TODO add unintended-upgrades
