- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    home_dir: "{{ lookup('env', 'HOME') }}"
    dest_key: "{{ home_dir }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update apt
    become: true
    ansible.builtin.apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
    - core
    - node
  tasks:
  - name: Setup SSH
    ansible.builtin.import_tasks:
      file: tasks/ssh.yml
  - name: Setup git config
    ansible.builtin.import_tasks:
      file: tasks/git.yml
  - name: Install Node.js
    ansible.builtin.import_tasks:
      file: tasks/node.yml
    become: true
  - name: Setup aliases
    ansible.builtin.import_tasks:
      file: tasks/aliases.yml
