- name: Check if deno is installed # noqa: no-changed-when
  ansible.builtin.command: deno --version
  register: deno_exists
  ignore_errors: true
  tags:
    - deno

- name: Download Deno installer
  become: true
  when: deno_exists is failed
  ansible.builtin.get_url:
    url: https://deno.land/x/install/install.sh
    dest: /tmp/deno.install.sh
    mode: 0755
    force: true
  tags:
    - deno

- name: Install deno # noqa: command-instead-of-shell
  when: deno_exists is failed
  ansible.builtin.shell: /tmp/deno.install.sh
  tags:
    - deno

- name: Ensure deno is added to PATH
  ansible.builtin.blockinfile:
    dest: '{{ home_dir }}/.bashrc'
    block: |
      if [ -d ~/.deno/bin ]; then
        PATH=$PATH:~/.deno/bin
      fi
    marker: '# {mark} ANSIBLE MANAGED BLOCK - .deno/bin'
    insertafter: EOF
    create: true
    mode: 0644
  tags:
    - deno
