- name: Check if pyenv is installed, the python version manmager # noqa: no-changed-when
  ansible.builtin.command: pyenv version
  register: pyenv_exists
  ignore_errors: true
  tags:
    - python

- name: Download pyenv installer
  when: pyenv_exists is failed
  ansible.builtin.get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv.run.sh
    mode: 0755
    force: true
  tags:
    - python

- name: Install pyenv, the python package manager # noqa: command-instead-of-shell
  when: pyenv_exists is failed
  become: false
  ansible.builtin.shell: /tmp/pyenv.run.sh
  tags:
    - python

- name: Ensure pyenv is available
  ansible.builtin.blockinfile:
    dest: "{{ home_dir }}/.bashrc"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - pyenv"
    insertafter: EOF
    create: true
    mode: 0644
  tags:
    - python
